application: saimixins
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /assets/img
  static_dir: assets/img

- url: /assets/img/(.*)
  static_files: assets/img/\1
  upload: assets/img/(.*)

libraries:
- name: webapp2
  version: "2.5.2"
